/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Tutorial
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OperationCd,
    OperationCdFromJSON,
    OperationCdFromJSONTyped,
    OperationCdToJSON,
} from './';

/**
 * リクエスト 操作ログ
 * @export
 * @interface RequestOperationLog
 */
export interface RequestOperationLog {
    /**
     * 
     * @type {OperationCd}
     * @memberof RequestOperationLog
     */
    operationCd: OperationCd;
}

export function RequestOperationLogFromJSON(json: any): RequestOperationLog {
    return RequestOperationLogFromJSONTyped(json, false);
}

export function RequestOperationLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestOperationLog {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'operationCd': OperationCdFromJSON(json['operationCd']),
    };
}

export function RequestOperationLogToJSON(value?: RequestOperationLog | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'operationCd': OperationCdToJSON(value.operationCd),
    };
}

