/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Tutorial
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * レスポンス アンケートの状態
 * @export
 * @interface ResponseItemQuestionnaireStatus
 */
export interface ResponseItemQuestionnaireStatus {
    /**
     * アンケートid
     * @type {number}
     * @memberof ResponseItemQuestionnaireStatus
     */
    questionnaireId: number;
    /**
     * 
     * @type {ResponseItemQuestionnaireStatus}
     * @memberof ResponseItemQuestionnaireStatus
     */
    status: ResponseItemQuestionnaireStatus;
}

export function ResponseItemQuestionnaireStatusFromJSON(json: any): ResponseItemQuestionnaireStatus {
    return ResponseItemQuestionnaireStatusFromJSONTyped(json, false);
}

export function ResponseItemQuestionnaireStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseItemQuestionnaireStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'questionnaireId': json['questionnaireId'],
        'status': ResponseItemQuestionnaireStatusFromJSON(json['status']),
    };
}

export function ResponseItemQuestionnaireStatusToJSON(value?: ResponseItemQuestionnaireStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'questionnaireId': value.questionnaireId,
        'status': ResponseItemQuestionnaireStatusToJSON(value.status),
    };
}

