openapi: 3.0.0
info:
  title: OpenAPI Tutorial
  description: OpenAPI Tutorial by halhorn
  version: 0.0.0
servers:
  - url: http://localhost:80/api/v1
    description: 開発用
paths:
  /log/operation:
    post:
      tags:
        - 'log'
      summary: 操作ログの送信を行います。
      description: 詳細内容
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestOperationLog'
      responses:
        '200':
          description: OK
          content: {}
  /questionnaires/{questionnairesType}/status:
    get:
      tags:
        - 'questionnaires'
      summary: アンケートの回答状態を取得します。
      description: 詳細内容
      parameters:
        - in: path
          name: questionnairesType
          required: true
          schema:
            $ref: '#/components/schemas/questionnaireType'
      responses:
        '200':
          description: アンケートの回答状態
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseQuestionnaireStatus'
  /questionnaires/{questionnairesType}:
    post:
      tags:
        - 'questionnaires'
      summary: アンケートの登録を行います。
      description: 詳細内容
      parameters:
        - in: path
          name: questionnairesType
          required: true
          schema:
            $ref: '#/components/schemas/questionnaireType'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestQuestionnaireCreate'
      responses:
        '200':
          description: OK
          content: {}

components:
  schemas:
    responseQuestionnaireStatus:
      description: レスポンス アンケートの状態
      type: object
      properties:
        questionnaireType:
          $ref: '#/components/schemas/questionnaireType'
        status:
          $ref: '#/components/schemas/questionnaireStatus'
      required:
        - questionnaireId
        - status
    requestOperationLog:
      description: リクエスト 操作ログ
      type: object
      properties:
        operationCd:
          $ref: '#/components/schemas/operationCd'
      required:
        - operationCd
    requestQuestionnaireCreate:
      description: リクエスト アンケート登録
      type: object
      properties:
        jsonAnswer:
          type: string
          description: ' json形式の回答データ'
        isCanceld:
          type: boolean
          description: キャンセルフラグ
      required:
        - jsonAnswer
        - isCanceld
    questionnaireType:
      description: |
        ■アンケートの種類  
        FIRST_TEST: 初回テスト
      enum: [1]
      x-enum-varnames: [FIRST_TEST]
    questionnaireStatus:
      description: |
        ■アンケートの回答状態  
        ANSWERED: 回答済  
        UNANSWERED: 未回答
        INELIGIBILITY: 不適格
      enum: [1, 2, 3]
      x-enum-varnames: [ANSWERED, UNANSWERED, INELIGIBILITY]
    operationCd:
      description: |
        ■操作コード  
        ENABLE_SENSOR: センサーを有効にする  
        CALIBRATION: キャリブレーション  
        CALIBRATION_BEFORE_SETTING: 直前設定を使う  
        CALIBRATION_NEXT_1: キャリブレーション1 次へ  
        CALIBRATION_NEXT_2: キャリブレーション2 次へ  
        MAX_14_G: Max1.4G  
        MAX_10_G: Max1.0G  
        VOICE_OUTPUT_ON: 音声出力ON  
        VOICE_OUTPUT_OFF: 音声出力OFF  
        GBOWL: GBowl  
        GINDICATOR: GIndicator
      enum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
      x-enum-varnames:
        [
          ENABLE_SENSOR,
          CALIBRATION,
          CALIBRATION_BEFORE_SETTING,
          CALIBRATION_NEXT_1,
          CALIBRATION_NEXT_2,
          MAX_14_G,
          MAX_10_G,
          VOICE_OUTPUT_ON,
          VOICE_OUTPUT_OFF,
          GBOWL,
          GINDICATOR,
        ]
