/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Tutorial
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * ■アンケートの回答状態  
 * ANSWERED: 回答済  
 * UNANSWERED: 未回答
 * INELIGIBILITY: 不適格
 * @export
 * @enum {string}
 */
export enum QuestionnaireStatus {
    ANSWERED = 1,
    UNANSWERED = 2,
    INELIGIBILITY = 3
}

export function QuestionnaireStatusFromJSON(json: any): QuestionnaireStatus {
    return QuestionnaireStatusFromJSONTyped(json, false);
}

export function QuestionnaireStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionnaireStatus {
    return json as QuestionnaireStatus;
}

export function QuestionnaireStatusToJSON(value?: QuestionnaireStatus | null): any {
    return value as any;
}

