/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Tutorial
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    QuestionnaireStatus,
    QuestionnaireStatusFromJSON,
    QuestionnaireStatusFromJSONTyped,
    QuestionnaireStatusToJSON,
    QuestionnaireType,
    QuestionnaireTypeFromJSON,
    QuestionnaireTypeFromJSONTyped,
    QuestionnaireTypeToJSON,
} from './';

/**
 * レスポンス アンケートの状態
 * @export
 * @interface ResponseQuestionnaireStatus
 */
export interface ResponseQuestionnaireStatus {
    /**
     * 
     * @type {QuestionnaireType}
     * @memberof ResponseQuestionnaireStatus
     */
    questionnaireType?: QuestionnaireType;
    /**
     * 
     * @type {QuestionnaireStatus}
     * @memberof ResponseQuestionnaireStatus
     */
    status: QuestionnaireStatus;
}

export function ResponseQuestionnaireStatusFromJSON(json: any): ResponseQuestionnaireStatus {
    return ResponseQuestionnaireStatusFromJSONTyped(json, false);
}

export function ResponseQuestionnaireStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseQuestionnaireStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'questionnaireType': !exists(json, 'questionnaireType') ? undefined : QuestionnaireTypeFromJSON(json['questionnaireType']),
        'status': QuestionnaireStatusFromJSON(json['status']),
    };
}

export function ResponseQuestionnaireStatusToJSON(value?: ResponseQuestionnaireStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'questionnaireType': QuestionnaireTypeToJSON(value.questionnaireType),
        'status': QuestionnaireStatusToJSON(value.status),
    };
}

