/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Tutorial
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    RequestOperationLog,
    RequestOperationLogFromJSON,
    RequestOperationLogToJSON,
} from '../models';

export interface LogOperationPostRequest {
    requestOperationLog: RequestOperationLog;
}

/**
 * LogApi - interface
 * 
 * @export
 * @interface LogApiInterface
 */
export interface LogApiInterface {
    /**
     * 詳細内容
     * @summary 操作ログの送信を行います。
     * @param {RequestOperationLog} requestOperationLog 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LogApiInterface
     */
    logOperationPostRaw(requestParameters: LogOperationPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     * 詳細内容
     * 操作ログの送信を行います。
     */
    logOperationPost(requestParameters: LogOperationPostRequest, initOverrides?: RequestInit): Promise<void>;

}

/**
 * 
 */
export class LogApi extends runtime.BaseAPI implements LogApiInterface {

    /**
     * 詳細内容
     * 操作ログの送信を行います。
     */
    async logOperationPostRaw(requestParameters: LogOperationPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.requestOperationLog === null || requestParameters.requestOperationLog === undefined) {
            throw new runtime.RequiredError('requestOperationLog','Required parameter requestParameters.requestOperationLog was null or undefined when calling logOperationPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/log/operation`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestOperationLogToJSON(requestParameters.requestOperationLog),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 詳細内容
     * 操作ログの送信を行います。
     */
    async logOperationPost(requestParameters: LogOperationPostRequest, initOverrides?: RequestInit): Promise<void> {
        await this.logOperationPostRaw(requestParameters, initOverrides);
    }

}
